#!/bin/bash
#
# Run RNA-seq alignment, quantification, and QC using nf-core/rnaseq.
# Reads the samplesheet generated by fetchngs in Step 1.
# Usage: sbatch scripts/run_rnaseq.sh
#
#SBATCH --job-name=rnaseq
#SBATCH --output=logs/rnaseq_%j.log
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time=48:00:00
#SBATCH --partition=short,medium,long

cd "$SLURM_SUBMIT_DIR"

module load Singularity
module load Java

./nextflow -log logs/nextflow_rnaseq.log \
    run nf-core/rnaseq \
    -r 3.23.0 \
    -profile cheaha \
    -params-file params.rnaseq.yml

# -r 3.23.0              Pin the pipeline version
# -profile cheaha         Load Cheaha HPC config (Singularity + SLURM)
# -params-file            Read pipeline parameters from YAML file
